theme: jekyll-theme-minimal
title: Shahat's homepage
description: Shahat Zaman, based in Buffalo, NY — known generally as shahat — makes bedroom indie pop style music in, you guessed it, his bedroom. He is also a 3D Arist and Programmer that has years of experience.

